/*
 * Regenerates _data/media.yml — the orientation/dimension facts the gallery
 * includes read, so pages don't have to hard-code them. Run `just media`.
 *
 * Videos: YouTube publishes no usable orientation anywhere a page can reach it.
 * Its own oEmbed answers `200x113` for every video (the *embed* box, not the
 * video), every thumbnail is a 1280x720 composite, and the IFrame API exposes
 * no dimensions. What does work is the Shorts URL: /shorts/<id> answers 200 for
 * a vertical video and 303-redirects to /watch for a landscape one. That needs
 * a server-side request — CORS blocks it in the browser and GitHub Pages allows
 * no Jekyll plugins — so it happens here, at authoring time, and the answer is
 * committed.
 *
 * Images: dimensions come straight out of the JPEG header.
 */
import { readFile, writeFile, readdir } from "node:fs/promises";
import { join, extname } from "node:path";

const REPO = new URL("..", import.meta.url).pathname;

async function isVertical(id) {
  const res = await fetch(`https://www.youtube.com/shorts/${id}`, {
    redirect: "manual",
    headers: { "user-agent": "Mozilla/5.0" },
  });
  if (res.status === 200) return true;
  if (res.status >= 300 && res.status < 400) return false;
  throw new Error(`unexpected status ${res.status} for ${id}`);
}

/*
 * The poster a link preview should point at. maxresdefault is missing for
 * plenty of uploads — the gallery tiles already carry a fallback chain for
 * exactly that — and an og:image pointing at a 404 renders as no preview at
 * all. Resolved here and committed, so neither the share-page generator nor
 * the test suite has to reach YouTube to know which one is real.
 */
const POSTERS = ["maxresdefault.jpg", "hq720.jpg", "mqdefault.jpg"];

async function poster(id) {
  for (const file of POSTERS) {
    const res = await fetch(`https://i.ytimg.com/vi/${id}/${file}`);
    if (!res.ok) continue;
    const size = jpegSize(Buffer.from(await res.arrayBuffer()));
    if (size) return { file, width: size.width, height: size.height };
  }
  throw new Error(`no usable poster for ${id} — tried ${POSTERS.join(", ")}`);
}

/** Width/height from a JPEG's SOF marker. */
function jpegSize(buf) {
  let i = 2;
  while (i < buf.length - 9) {
    if (buf[i] !== 0xff) { i += 1; continue; }
    const marker = buf[i + 1];
    if (marker >= 0xc0 && marker <= 0xc3) {
      return { height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7) };
    }
    if (marker === 0xd8 || marker === 0xd9 || (marker >= 0xd0 && marker <= 0xd7)) { i += 2; continue; }
    i += 2 + buf.readUInt16BE(i + 2);
  }
  return null;
}

const gcd = (a, b) => (b ? gcd(b, a % b) : a);

async function markdownFiles(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (/^(_site|node_modules|vendor|\.git|_drafts)$/.test(entry.name)) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) await markdownFiles(path, out);
    else if (extname(entry.name) === ".md") out.push(path);
  }
  return out;
}

// --- videos referenced anywhere in the site ---------------------------------
const ids = new Set();
const addId = (raw) =>
  ids.add(raw.replace(/^.*(?:v=|youtu\.be\/|shorts\/)/, "").split(/[&?]/)[0]);

for (const file of await markdownFiles(REPO)) {
  const text = await readFile(file, "utf8");
  for (const m of text.matchAll(/\{%\s*include\s+video\s+[^%]*id=["']([^"']+)["']/g)) addId(m[1]);
}

/*
 * The /led gallery's items moved into _data/led.yml so `just share` could walk
 * the same list, and its include is now `id=item.video` — which the scan above
 * cannot see. Without this, a `just media` run would quietly write a media.yml
 * with no videos in it and every tile would fall back to landscape.
 */
for (const m of (await readFile(join(REPO, "_data/led.yml"), "utf8")).matchAll(
  /^\s*-?\s*video:\s*(\S+)/gm,
)) addId(m[1]);

const videos = {};
for (const id of [...ids].sort()) {
  const vertical = await isVertical(id);
  const p = await poster(id);
  videos[id] = {
    orientation: vertical ? "portrait" : "landscape",
    aspect: vertical ? "9:16" : "16:9",
    poster: p.file,
    poster_width: p.width,
    poster_height: p.height,
  };
  console.log(`  ${id}  ${videos[id].orientation}  ${p.file} ${p.width}x${p.height}`);
}

// --- images in /img ----------------------------------------------------------
const images = {};
for (const name of (await readdir(join(REPO, "img"))).sort()) {
  const size = jpegSize(await readFile(join(REPO, "img", name)));
  if (!size) { console.warn(`  ${name}  (no JPEG header — skipped)`); continue; }
  const { width, height } = size;
  const d = gcd(width, height);
  images[`/img/${name}`] = {
    width, height,
    aspect: `${width / d}:${height / d}`,
    orientation: height > width ? "portrait" : "landscape",
  };
  console.log(`  ${name}  ${width}x${height}  ${images[`/img/${name}`].orientation}`);
}

const yaml = [
  "# Generated by `just media` (scripts/probe-media.mjs). Do not edit by hand.",
  "#",
  "# Video orientation cannot be read from any endpoint a page can reach —",
  "# see the script's header. It is probed server-side and committed here.",
  "#",
  "# `poster` is which of YouTube's thumbnails actually exists for that id, and",
  "# its real pixel size: og:image for a share page points at it, and a preview",
  "# whose image 404s shows no picture at all.",
  "videos:",
  ...Object.entries(videos).map(([id, v]) =>
    `  "${id}": { orientation: ${v.orientation}, aspect: "${v.aspect}", ` +
    `poster: "${v.poster}", poster_width: ${v.poster_width}, poster_height: ${v.poster_height} }`),
  "images:",
  ...Object.entries(images).map(([path, i]) =>
    `  "${path}": { orientation: ${i.orientation}, aspect: "${i.aspect}", width: ${i.width}, height: ${i.height} }`),
  "",
].join("\n");

await writeFile(join(REPO, "_data/media.yml"), yaml);
console.log(`\nwrote _data/media.yml — ${Object.keys(videos).length} videos, ${Object.keys(images).length} images`);
