/*
 * Regenerates _data/media.yml — the orientation/dimension facts the gallery
 * includes read, so pages don't have to hard-code them. Run `just media`.
 *
 * Videos: YouTube publishes no usable orientation anywhere a page can reach it.
 * Its own oEmbed answers `200x113` for every video (the *embed* box, not the
 * video), every thumbnail is a 1280x720 composite, and the IFrame API exposes
 * no dimensions. What does work is the Shorts URL: /shorts/<id> answers 200 for
 * a vertical video and 303-redirects to /watch for a landscape one. That needs
 * a server-side request — CORS blocks it in the browser and GitHub Pages allows
 * no Jekyll plugins — so it happens here, at authoring time, and the answer is
 * committed.
 *
 * Images: dimensions come straight out of the JPEG header.
 */
import { readFile, writeFile, readdir } from "node:fs/promises";
import { join, extname } from "node:path";

const REPO = new URL("..", import.meta.url).pathname;

async function isVertical(id) {
  const res = await fetch(`https://www.youtube.com/shorts/${id}`, {
    redirect: "manual",
    headers: { "user-agent": "Mozilla/5.0" },
  });
  if (res.status === 200) return true;
  if (res.status >= 300 && res.status < 400) return false;
  throw new Error(`unexpected status ${res.status} for ${id}`);
}

/** Width/height from a JPEG's SOF marker. */
function jpegSize(buf) {
  let i = 2;
  while (i < buf.length - 9) {
    if (buf[i] !== 0xff) { i += 1; continue; }
    const marker = buf[i + 1];
    if (marker >= 0xc0 && marker <= 0xc3) {
      return { height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7) };
    }
    if (marker === 0xd8 || marker === 0xd9 || (marker >= 0xd0 && marker <= 0xd7)) { i += 2; continue; }
    i += 2 + buf.readUInt16BE(i + 2);
  }
  return null;
}

const gcd = (a, b) => (b ? gcd(b, a % b) : a);

async function markdownFiles(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (/^(_site|node_modules|vendor|\.git|_drafts)$/.test(entry.name)) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) await markdownFiles(path, out);
    else if (extname(entry.name) === ".md") out.push(path);
  }
  return out;
}

// --- videos referenced anywhere in the site ---------------------------------
const ids = new Set();
for (const file of await markdownFiles(REPO)) {
  const text = await readFile(file, "utf8");
  for (const m of text.matchAll(/\{%\s*include\s+video\s+[^%]*id=["']([^"']+)["']/g)) {
    ids.add(m[1].replace(/^.*(?:v=|youtu\.be\/|shorts\/)/, "").split(/[&?]/)[0]);
  }
}

const videos = {};
for (const id of [...ids].sort()) {
  const vertical = await isVertical(id);
  videos[id] = { orientation: vertical ? "portrait" : "landscape", aspect: vertical ? "9:16" : "16:9" };
  console.log(`  ${id}  ${videos[id].orientation}`);
}

// --- images in /img ----------------------------------------------------------
const images = {};
for (const name of (await readdir(join(REPO, "img"))).sort()) {
  const size = jpegSize(await readFile(join(REPO, "img", name)));
  if (!size) { console.warn(`  ${name}  (no JPEG header — skipped)`); continue; }
  const { width, height } = size;
  const d = gcd(width, height);
  images[`/img/${name}`] = {
    width, height,
    aspect: `${width / d}:${height / d}`,
    orientation: height > width ? "portrait" : "landscape",
  };
  console.log(`  ${name}  ${width}x${height}  ${images[`/img/${name}`].orientation}`);
}

const yaml = [
  "# Generated by `just media` (scripts/probe-media.mjs). Do not edit by hand.",
  "#",
  "# Video orientation cannot be read from any endpoint a page can reach —",
  "# see the script's header. It is probed server-side and committed here.",
  "videos:",
  ...Object.entries(videos).map(([id, v]) =>
    `  "${id}": { orientation: ${v.orientation}, aspect: "${v.aspect}" }`),
  "images:",
  ...Object.entries(images).map(([path, i]) =>
    `  "${path}": { orientation: ${i.orientation}, aspect: "${i.aspect}", width: ${i.width}, height: ${i.height} }`),
  "",
].join("\n");

await writeFile(join(REPO, "_data/media.yml"), yaml);
console.log(`\nwrote _data/media.yml — ${Object.keys(videos).length} videos, ${Object.keys(images).length} images`);
